acme_store_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }

_create_product:
    path: /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

_show_product:
    path: /show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }